awsdocs/amazon-api-gateway-developer-guide

doc_source/api-gateway-enable-compression.md

CLI command to create a rest API with compression enabled is incorrect, the option must be:
--minimum-compression-size <INTEGER> 
and not  --minimumCompressionSize as provided in the doc
Reference:
https://docs.aws.amazon.com/cli/latest/reference/apigateway/create-rest-api.html

Modifying incorrect CLI Command

---

doc_source/api-gateway-payload-encodings.md

A typo - replacing period with a colon in the following sentence:
A text payload is a `UTF-8`\-encoded JSON string\
,
and a binary payload is anything other than a text payload\.

Fix typo - colon instead of period

---

doc_source/api-gateway-lambda-authorizer-output.md

Fix ARN typo

---

doc_source/apigateway-private-apis.md

n/a
Fixed the cURL command example in the "**Invoking Your API Using Public DNS Names**":
- the region of the vpc endpoint DNS should be us-west-1
- the resource name is /pets and not /get
- there should be a space after the -H option (even if it works without it)
- we could add a space after the 'Host:' header as this is usually how HTTP headers are passed (even if RFC 7230 defines it as optional)

Fixed cURL command example to invoke API with Public DNS

---

doc_source/api-gateway-lambda-authorizer-output.md

It is currently unclear from the documentation and error messages whether the Lambda Authorizer should return a dictionary/object, or a string containing JSON.

Return type for a Lambda Authorizer

---

doc_source/apigateway-websocket-api-selection-expressions.md

Description of changes: The expression invalidly had a parenthesis where it should have had a curly brace, and the dash in the expression, which is a static value, was not present in the evaluated result.

Fix WebSocket selection expression and evaluated result

---

doc_source/api-gateway-enable-compression.md

As raised/discovered through a support case, API-GW only considers the first type in the header when determining encoding of the content, so it will not compress if it comes across an unsupported encodings such `br` or a malformed encoding format.

Add note about Accept-Encoding format priorities

---

doc_source/set-up-logging.md

Cloudwatch logging permissions must be set for API Gateway in each region. Add note to reflect this.
Added a note that API Gateway settings are region-specific, not account-wide.

clarify permissions for logging are regional

---

doc_source/apigateway-resource-policies-examples.md

The documentation mentioned that the user and the root account belonged to account-id-2, however the policy example mentioned account-id which was not mentioned in the text.
Updated the ARN for user Alice with the correct reference to account account-id-2

Updating the ARN of the user in the IAM example

---

doc_source/getting-started-lambda-non-proxy-integration.md

*Issue 1: Option "Create new role from template(s)"* is obsoleted from console. When select Lambda Execution role 
*Description of changes: Option "Create a new role from AWS policy templates" was updated as new choice.*

Update Lambda function Execution role option in documentation.

---

doc_source/set-up-lambda-integration-async.md

- The current doc seemed to mix up method request and integration request (e.g. it had mapping against method request rather than integration request).
- The static vs dynamic mapping was specified but it wasn't clear that the header declaration in the method request ('integration request' in the current doc) isn't required at all if using the static mapping.

Correct and clarify Method Request and Integration Requests for async calls

---

doc_source/apigateway-enable-cognito-user-pool.md

In order to use an access token with OAuth Scopes for an API method. The token validation expression must be blank/undefined. Otherwise the API will reject the request with a 401 error code due to the Access token not containing an `aud` field. 
This additional information in the documentation is required as this caveat is not documented anywhere and must be derived from the token structure and this `aud` field validation.

Added: clarification of validation expression use

---

doc_source/set-up-lambda-proxy-integrations.md

This is shown in the event but isn't in the HTTP request, confusingly. As far as I understand, this change is what the request should look like. I haven't tested it.

Use multivalueName in request

---

doc_source/apigateway-resource-policies-examples.md

This change adds an example for using VpcSourceIp on the API Gateway resource policy to allow customers filtering the traffic to a Private API Gateway API by CIDRs. As VPC Endpoints re-writes the SourceIP of a request, it is necessary to use the VpcSourceIp condition key to obtain the IP of the original caller.
The current examples do not mention the behavior that aws:SourceIp condition does not work when using VPC Endpoints as for private APIs.
Added an example that uses the aws:VpcSourceIp condition to properly filter a request against the original caller IP address.

Example for VpcSourceIp for Resource Policies

---

doc_source/integration-passthrough-behaviors.md

None
The correct value of the param is `WHEN_NO_TEMPLATES`. The API rejects the value `WHEN_NO_TEMPLATE`.
Refs:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-extensions-integrations.html
https://docs.aws.amazon.com/apigateway/api-reference/resource/integration/

Fix passthrough option in docs

---

doc_source/http-api-develop-integrations-lambda.md

Like in 1.0 payloads, escaped `pathParameters` are also visible in 2.0 payloads but they were not present in the example.

pathParameters are also visible in 2.0 payloads

---

doc_source/apigateway-use-lambda-authorizer.md

Propose change at step 16 of "EXAMPLE: Create a Token-Based Lambda Authorizer Function"  
The original step indicate to enter for *Token Source* **tokenHeader**.  
However, even though this works while testing the authoriser in the APIGW Console, the header used by the sample function provided in the example is **authorizationToken**. Furthermore, when testing the API using for example Postman, and using the header **authorizationToken** as suggested [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html), the authorisation fails.  
By entering **authorizationToken** in *Token Source* when configuring the authoriser this can be resolved.
NOTE:
The same change should also be applied at …

Correction of 1 input term

---

doc_source/apigateway-use-lambda-authorizer.md

Similar to my previous pull request [Correction of 1 input term #61 ](https://github.com/awsdocs/amazon-api-gateway-developer-guide/pull/61) 
Propose the same change also at step 19 of "EXAMPLE: Create a Token-Based Lambda Authorizer Function"
"For the tokenHeader value, enter allow" should become:  
"For the authorizationToken value, enter allow"
Apologies for the double PR but I didn't notice this at first

Correction of 1 input term - 2

---

doc_source/http-api-jwt-authorizer.md

N/A
Provided example of create-authorizer has incorrect syntax, edited command (specifically jwt-configuration) to reflect proper syntax as stated [in documentation](https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/create-authorizer.html).

fix for create-authorizer cli command

---

doc_source/request-response-data-mappings.md

Velocity Template Language link was resulting in a 404. I believe I have found the correct reference.  I've also switched the link to https

Fixed VTL Reference Link

---

doc_source/api-gateway-mapping-template-reference.md

The example had inconsistent casing including kebab-case and snake_case.  The template provided by the API Gateway console uses kebab-case for a very similar example so I've copied that example here.  Using that example also adds Cognito context and alphabetizes the variables.

Consistent casing in $context example

---

doc_source/api-gateway-payload-encodings.md

This tip could help future developers who are looking to solve the problem of serving images from S3 via API Gateway
Changed the Integration link to IntegrationRequest, to make it consistent with the IntegrationResponse link and make it more obvious which integration it is referring to
Added a tip on how to serve images from S3 via API Gatway as it could save developers time figuring this out in the future

Include a tip on how to serve images from S3

---

doc_source/http-api-develop-integrations-lambda.md

The documentation states:
> Format `2.0` doesn't have `multiValueHeaders` or `multiValueQueryStringParameters` fields\. Duplicate headers are combined with commas and included in the `headers` field\. Duplicate query strings are combined with commas and included in the `queryStringParameters` field.
But then the example contradicts that by skipping the 1st value of the header.
**Please review carefully**, I haven't tested. I am just assuming this is what should happen based on the sentence above. But I believe that either way there is a contradiction to fix here.
---

Fix multiple-value header in payload v2

---

doc_source/http-api-develop-integrations-private.md

*Issue #, if available:* N/A
Fixed `apigatewayv2 create-integration` AWS CLI command for HTTP API private integrations in **http-api-develop-integrations-private.md** to include `payload-format-version`. This is [required for HTTP APIs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/create-integration.html): 

Fixed apigatewayv2 create-integration AWS CLI command for HTTP APIs

---

doc_source/http-api-develop-integrations-lambda.md

I reformatted the JSON examples, it's really handy being able to copy these and paste into Lambda Event for testing, or pulling them in as an example for unit tests, but due to them being invalid JSON they fail and require being reformatted first.
---

Reformatted the JSON examples

---

doc_source/apigateway-private-apis.md

The example of REST private api creation from aws-cli has both command and result in the same markdown snippet box.
The commit split it in two box, one for the command and one for the result.
It should result more clear now.

Fix REST private api creation from aws-cli

---

doc_source/http-api-develop-integrations-lambda.md

It's unusable
&nbsp;&nbsp;&nbsp;with
&nbsp;bad
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indentation

Correctly indent JSON in Lambda example events

---

doc_source/http-api-develop-integrations-lambda.md

The sample input does not validate because base64 decoding the body fails.
Alternatively, the body could be base64 encoded but that probably removes the utility of having a readable string

The body is not actually base64 encoded

---

doc_source/apigateway-resource-policies.md

Resource and identity policies are both a type of IAM policy, so the documentation is incorrect in assuming a resource policy is different from an IAM policy.  The documentation really means "identity policies". See: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_identity-vs-resource.html

replace "IAM policies" with "identity policies"

---

doc_source/http-api-develop-integrations-lambda.md

With the release of the Lambda authorizer for HTTP API Gateway, the example payload doesn't contain the new `lambda` properties passed down from the authorizer.

Update payload v2.0 with Lambda authorizer context

---

doc_source/integration-passthrough-behaviors.md

The closing parentheses are missing in the Integration passthrough behaviors example tables

Missing parenthesis in passthrough behavior tables

---

doc_source/api-gateway-swagger-extensions-request-validators.md

This particular extension generates an INFO message when importing using a command line. It's a good idea to update the documentation for similar extensions only working on certain APIs. But some of the extensions do work for any API, e.g. `x-amazon-apigateway-integration`
N/A
Added a warning about HTTP API

Certain extensions don't work for all API types

---

doc_source/apigateway-developer-portal.md

The description in this documentation seems to suggest the opposite to the description in the serverless application repository (api-gateway-dev-portal — version 4.1.0):
**This doc:**
```
UseRoute53Nameservers
Only applicable if you're creating a custom domain name for your developer portal. Specify true to skip creating a Route 53 HostedZone and RecordSet. You'll need to provide your own name server hosting in place of Route 53. Otherwise, leave this field set to false.
```
**api-gateway-dev-portal — version 4.1.0:**
```
UseRoute53Nameservers
Only applicable if creating a custom domain name for your dev portal. Defaults to false, and you'll need to provide your own nameserver hosting. If set to true, a Route53 HostedZone and RecordSet are created for you.
```
**I'm proposing to change …

Fix for UserRoute53Nameservers description

---

doc_source/apigateway-integrate-with-cognito.md

N/A
In the original version the link to the cognito SDK points to the discontinued, standalone version. This change alters the link to point to the cognito SDK that is a part of amplify and is still under active development.

Link to actively developed SDK

---

doc_source/http-api-throttling.md

Presumably this was supposed to say that route throttling limits cannot exceed the account-level limits.
*Issue #, if available: None
*Description of changes: Fix typo regarding route-level vs account-level throttling limits.

Update http-api-throttling.md to fix typo

---

doc_source/security_iam_id-based-policy-examples.md

Just noticed this condition key is mispelled when looking through the APIGW docs.

✏️ Fix Typo in Condition Key

---

doc_source/http-api-lambda-authorizer.md

Adding note to troubleshooting tips. 
In the case where a request made does not include the identity source, the api gateway returns a 401, without a hint as to why. There's no authoerizer error because the authorizer is never called. This document, as it should, instructs people to use the Authorization header, however it's not something included when running a quick curl / browser GET test. 
In this case it kind of fails silently, and isnt obvious to figure out. This note would have saved me some time. My lambda didnt need a specific header, it authenticates the request in an unconventional way.

Troubleshooting addition for Lambda Authorizer

---

doc_source/http-api-develop-integrations-lambda.md

The example payload shows the format of payload that is sent from API gateway *to* lambda integration. The message in the body might give a different idea.

Change example payload's body to avoid confusion

---

doc_source/api-gateway-known-issues.md

During some testing today I noticed that the AWS Gateway does not except "anyOf" and "allOf" alongside "oneOf" for schema validation. See OpenAPI 3.0 documentation on data model validation for more details: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
*Issue #, if available:* None
*Description of changes:* added the other two options available in OpenAPI for data type validation (anyOf and allOf) to the known issues list alongside "oneOf"

Update OpenAPI 3.0 known issues

---

doc_source/http-api-vs-rest.md

Merging API Definition is an awesome feature but is available only in REST ApiGateway and not in HTTP ApiGateway.
I have multiple OpenAPI specifications (each service has its own spec file). Earlier, I need to merge all those spec files into one big spec file and this is used for deploying api gateway which is maintained in a separate repo and hence a separate deployment.
Then I came to know about the ability to import an OpenAPI file to update an existing API definition using merge mode. Using this approach, I can just initiate gateway changes together in same deployment pipeline. Also free from merging and maintaining big swagger.
But this is available only in the REST API gateway and not in the HTTP API gateway.

REST vs HTTP Api - Merging API Definition

---

doc_source/api-gateway-swagger-extensions-authorizer.md

- Update a handful of references where OpenAPI 2.0 `securityDefinitions` is used. This section was renamed to `securitySchemes` and moved inside `components` to in OpenAPI 3.0. Source: [Changes from OpenAPI 2.0](https://swagger.io/docs/specification/authentication/)
- Update the OpenAPI examples indention to be consistent with 2 space

docs: specify openapi 2.0 and minor indention fixes
