awsdocs/amazon-api-gateway-developer-guide

- doc_source/apigateway-private-apis.md
> Fixed typo 'to to'

- doc_source/view-cloudwatch-log-events-in-cloudwatch-console.md
Description of changes: Add missing word 'delete' to complete sentence.
> add missing word

- doc_source/api-gateway-create-api-as-simple-proxy-for-lambda.md
Description of changes:
- Changed variable declarations to use let instead of var to keep consistency.
- Simplified if conditionals to check for truthy values.
- Changed string concatenation to use string literals instead.
- Updated function to be async to match current default functions that are created by AWS lambda.
- Updated function to be an arrow function to match current default functions that are created by AWS lambda.
> Updated Node.js Hello World example function.

- doc_source/set-up-logging.md
Adding a note on the API Gateway docs to warn about the STS requirement
> STS must be enabled in order to enable API Logging

- doc_source/apigateway-how-to-call-websocket-api-connections.md
Updates websocket docs to reflect comments from: https://youtu.be/3SCdzzD0PdQ?t=718
> Adds GET and DELETE examples to websocket docs

- doc_source/api-gateway-known-issues.md
> fixed typo

- doc_source/delete-canary-deployment.md
Added missing braces to the JSON in the --patch-operations example
> Fixed the format of the update-stage --patch-operations example

- doc_source/api-gateway-mapping-template-reference.md
The code produces a "params" object, so reflect that in the rendered output.
> Align code and result

- doc_source/enable-cors-for-resource-using-swagger-importer-tool.md
> Add OpenAPI 3.0 samples

- doc_source/limits.md
I was confused by the wording on the quotas, this change makes it clearer what the quotas actually apply to
> Make quotas clearer

- doc_source/sell-api-as-saas-on-aws-marketplace.md
Project "API Gateway Developer Portal" is still maintained, but the integration with AWS Marketplace no longer works. Example should be removed as it confuses sellers.
> Removed sentence referring to broken example.

- doc_source/how-to-cors.md
Syntax error in NodeJs example
> Fixed syntax error in doc

- doc_source/api-gateway-api-endpoint-types.md
*Issue #, if available:* N/A
- Removed an extra period at end of sentence.
> Removed extra period at end of sentence

- doc_source/apigateway-use-lambda-authorizer.md
*Description of changes:* Updated the Postman url from www.getpostman.com to www.postman.com 🎸 🚀
> Update Postman URL

- doc_source/getting-started-with-private-integration.md
Just a simple fix, the doc was referring to the wrong step.
> Fix wrong step in doc

- doc_source/handle-errors-in-lambda-integration.md
Fix indentation in JSON code block
> Fix indentation in JSON code block

- doc_source/update-canary-deployment.md
*Issue : NA
*Description of changes:
Typo fixes on amazon-api-gateway-developer-guide
stageVariableOverides (one R)  => stageVariableOverrides (two R)
> Typo on update-canary-deployment.md

- doc_source/apigateway-how-to-call-websocket-api-connections.md
#142 
Adds missing indentation on js example
> fix(docs): add missing indentation

- doc_source/http-api-dynamo-db.md
*Issue #, if available: N/A
Change an "an" to an "a" in a sentence in the documentation describing deleting a Dynamo DB Table
> Fixed a small grammar mistake 

- doc_source/getting-started-lambda-non-proxy-integration.md
reqd to press the check box *then* select boolean options on params/headers
> update doc re: updated UX flow

- doc_source/http-api-develop-routes.md
After having spent an hour with several people reading this documentation and not seeing the issue although it was right in front of us, we thought we'd help the next team to get through this faster...
> Try to reduce confusion about `$default` route
